INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (2,E'COMMUNITY ELDERCARE OF SAN DIEGO',E'Community Eldercare Of San Diego',null,null,E'community-eldercare-of-san-diego');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (166,E'UCARE MINNESOTA',E'Ucare Minnesota',null,null,E'ucare-minnesota');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (238,E'ST. AGNES CONTINUING CARE CENTER',E'St. Agnes Continuing Care Center',null,null,E'st.-agnes-continuing-care-center');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (3,E'PHI LIFE',E'Phi Life',null,null,E'phi-life');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (4,E'CARE1ST HEALTH PLAN',E'Care1st Health Plan',null,null,E'care1st-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (5,E'SOUTH JERSEY HEALTH SYSTEM',E'South Jersey Health System',null,null,E'south-jersey-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (6,E'AVMED',E'Avmed',null,null,E'avmed');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (7,E'WELLCARE HEALTH PLANS',E'Wellcare Health Plans',null,null,E'wellcare-health-plans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (8,E'ULTIMATE HEALTH PLAN',E'Ultimate Health Plan',null,null,E'ultimate-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (9,E'MINISTRY HEALTH CARE',E'Ministry Health Care',null,null,E'ministry-health-care');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (10,E'NEW YORK STATE CATHOLIC HLTH PLAN',E'New York State Catholic Hlth Plan',null,null,E'new-york-state-catholic-hlth-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (11,E'PITTSBURGH CARE PARTNERSHIP',E'Pittsburgh Care Partnership',null,null,E'pittsburgh-care-partnership');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (12,E'CHEROKEE NATION COMPREHENSIVE CARE AGENCY',E'Cherokee Nation Comprehensive Care Agency',null,null,E'cherokee-nation-comprehensive-care-agency');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (13,E'CALIFORNIA PHYSICIANS'' SERVICES',E'California Physicians'' Services',null,null,E'california-physicians''-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (14,E'DEAN HEALTH SYSTEMS',E'Dean Health Systems',null,null,E'dean-health-systems');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (15,E'INLAND EMPIRE HEALTH PLAN',E'Inland Empire Health Plan',null,null,E'inland-empire-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (16,E'COVENANT HEALTH SYSTEM - HENDRICK HEALTH SYSTEM',E'Covenant Health System - Hendrick Health System',null,null,E'covenant-health-system---hendrick-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (17,E'KELSEY-SEYBOLD MEDICAL GROUP',E'Kelsey-Seybold Medical Group',null,null,E'kelsey-seybold-medical-group');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (18,E'COLORADO CHOICE HEALTH PLANS',E'Colorado Choice Health Plans',null,null,E'colorado-choice-health-plans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (19,E'MUNICH AMERICAN HOLDING CORPORATION',E'Munich American Holding Corporation',null,null,E'munich-american-holding-corporation');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (20,E'SATELLITE HEALTHCARE',E'Satellite Healthcare',null,null,E'satellite-healthcare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (21,E'IJKG OPCO',E'Ijkg Opco',null,null,E'ijkg-opco');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (22,E'INDEPENDENCE BLUE CROSS',E'Independence Blue Cross',null,null,E'independence-blue-cross');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (23,E'NORTH TEXAS SPECIALTY PHYSICIANS',E'North Texas Specialty Physicians',null,null,E'north-texas-specialty-physicians');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (24,E'SOUTH COUNTRY HEALTH ALLIANCE',E'South Country Health Alliance',null,null,E'south-country-health-alliance');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (25,E'SUMMA HEALTH SYSTEM',E'Summa Health System',null,null,E'summa-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (26,E'MARTIN''S POINT HEALTH CARE',E'Martin''S Point Health Care',null,null,E'martin''s-point-health-care');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (27,E'SUTTER HEALTH SACRAMENTO SIERRA REGION',E'Sutter Health Sacramento Sierra Region',null,null,E'sutter-health-sacramento-sierra-region');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (28,E'BLUE CROSS AND BLUE SHIELD OF FLORIDA',E'Blue Cross And Blue Shield Of Florida',null,null,E'blue-cross-and-blue-shield-of-florida');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (29,E'CIGNA',E'Cigna',null,null,E'cigna');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (30,E'HENRY FORD HEALTH SYSTEM',E'Henry Ford Health System',null,null,E'henry-ford-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (31,E'BLUECROSS BLUESHIELD OF SOUTH CAROLINA (BCBSSC)',E'Bluecross Blueshield Of South Carolina (Bcbssc)',null,null,E'bluecross-blueshield-of-south-carolina-(bcbssc)');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (32,E'BLUE CROSS AND BLUE SHIELD OF MINNESOTA',E'Blue Cross And Blue Shield Of Minnesota',null,null,E'blue-cross-and-blue-shield-of-minnesota');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (33,E'CARESOURCE',E'Caresource',null,null,E'caresource');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (34,E'LUTHERAN SENIORLIFE',E'Lutheran Seniorlife',null,null,E'lutheran-seniorlife');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (35,E'GEISINGER HEALTH SYSTEM',E'Geisinger Health System',null,null,E'geisinger-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (36,E'UNIVERSAL CARE',E'Universal Care',null,null,E'universal-care');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (37,E'GATEWAY HEALTH PLAN',E'Gateway Health Plan',null,null,E'gateway-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (38,E'ST. LUKE''S HEALTH SYSTEM',E'St. Luke''S Health System',null,null,E'st.-luke''s-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (39,E'MVP HEALTH PLAN',E'Mvp Health Plan',null,null,E'mvp-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (40,E'NEW YORK CITY HEALTH AND HOSPITALS CORP',E'New York City Health And Hospitals Corp',null,null,E'new-york-city-health-and-hospitals-corp');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (41,E'BLUECROSS BLUESHIELD OF ALABAMA',E'Bluecross Blueshield Of Alabama',null,null,E'bluecross-blueshield-of-alabama');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (42,E'MOUNTAIN STATES HEALTH ALLIANCE',E'Mountain States Health Alliance',null,null,E'mountain-states-health-alliance');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (43,E'QHP GROUP',E'Qhp Group',null,null,E'qhp-group');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (44,E'MOLINA HEALTHCARE',E'Molina Healthcare',null,null,E'molina-healthcare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (45,E'SAMARITAN HEALTH SERVICES',E'Samaritan Health Services',null,null,E'samaritan-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (46,E'SENIOR WHOLE HEALTH',E'Senior Whole Health',null,null,E'senior-whole-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (47,E'GROUP HEALTH COOPERATIVE',E'Group Health Cooperative',null,null,E'group-health-cooperative');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (233,E'ELDERHAUS',E'Elderhaus',null,null,E'elderhaus');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (243,E'CAREOREGON',E'Careoregon',null,null,E'careoregon');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (48,E'PRIMEWEST HEALTH SYSTEM',E'Primewest Health System',null,null,E'primewest-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (49,E'SOUNDPATH HEALTH',E'Soundpath Health',null,null,E'soundpath-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (50,E'ARDENT HEALTH SERVICES',E'Ardent Health Services',null,null,E'ardent-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (51,E'MARSHFIELD CLINIC',E'Marshfield Clinic',null,null,E'marshfield-clinic');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (52,E'PACE OF GUILFORD AND ROCKINGHAM COUNTIES',E'Pace Of Guilford And Rockingham Counties',null,null,E'pace-of-guilford-and-rockingham-counties');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (53,E'CAMBIA HEALTH SOLUTIONS',E'Cambia Health Solutions',null,null,E'cambia-health-solutions');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (54,E'HAWAII MEDICAL SERVICE ASSOCIATION',E'Hawaii Medical Service Association',null,null,E'hawaii-medical-service-association');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (55,E'METROPOLITAN HEALTH PLAN',E'Metropolitan Health Plan',null,null,E'metropolitan-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (56,E'SENIOR LIFE YORK',E'Senior Life York',null,null,E'senior-life-york');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (57,E'TOUCHSTONE HEALTH PARTNERSHIP',E'Touchstone Health Partnership',null,null,E'touchstone-health-partnership');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (58,E'BAYSTATE HEALTH',E'Baystate Health',null,null,E'baystate-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (59,E'COMMUNITY HOSPITAL FOUNDATION',E'Community Hospital Foundation',null,null,E'community-hospital-foundation');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (60,E'PROMEDICA HEALTH SYSTEM',E'Promedica Health System',null,null,E'promedica-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (61,E'SIMPLY HEALTHCARE HOLDINGS',E'Simply Healthcare Holdings',null,null,E'simply-healthcare-holdings');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (62,E'PACE OF THE SOUTHERN PIEDMONT',E'Pace Of The Southern Piedmont',null,null,E'pace-of-the-southern-piedmont');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (63,E'CAMBRIDGE HEALTH ALLIANCE',E'Cambridge Health Alliance',null,null,E'cambridge-health-alliance');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (64,E'CENTERLIGHT HEALTHCARE SYSTEM',E'Centerlight Healthcare System',null,null,E'centerlight-healthcare-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (65,E'LUTHERAN SOCIAL MINISTRIES OF NJ',E'Lutheran Social Ministries Of Nj',null,null,E'lutheran-social-ministries-of-nj');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (66,E'PIEDMONT HEALTHCARE',E'Piedmont Healthcare',null,null,E'piedmont-healthcare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (67,E'MOUNTAIN EMPIRE OLDER CITIZENS',E'Mountain Empire Older Citizens',null,null,E'mountain-empire-older-citizens');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (68,E'VISITING NURSE SERVICE OF NEW YORK',E'Visiting Nurse Service Of New York',null,null,E'visiting-nurse-service-of-new-york');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (69,E'ELDER SVC PLN/E BOSTON HEALTH CENTER',E'Elder Svc Pln/E Boston Health Center',null,null,E'elder-svc-pln/e-boston-health-center');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (70,E'FLORIDA PACE CENTERS',E'Florida Pace Centers',null,null,E'florida-pace-centers');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (71,E'SPECTRUM HEALTH SYSTEM',E'Spectrum Health System',null,null,E'spectrum-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (72,E'HUMANA',E'Humana',null,null,E'humana');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (73,E'HEALTHFIRST MANAGEMENT SERVICES',E'Healthfirst Management Services',null,null,E'healthfirst-management-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (74,E'NORTHLAND HEALTHCARE ALLIANCE',E'Northland Healthcare Alliance',null,null,E'northland-healthcare-alliance');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (75,E'SENIOR CARE CONNECTION',E'Senior Care Connection',null,null,E'senior-care-connection');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (76,E'HEALTH ALLIANCE MEDICAL PLANS',E'Health Alliance Medical Plans',null,null,E'health-alliance-medical-plans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (77,E'MEDICA HEALTH PLANS',E'Medica Health Plans',null,null,E'medica-health-plans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (78,E'AMERICA''S 1ST CHOICE NY HOLDINGS',E'America''S 1st Choice Ny Holdings',null,null,E'america''s-1st-choice-ny-holdings');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (79,E'ATRIO HEALTH PLANS',E'Atrio Health Plans',null,null,E'atrio-health-plans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (80,E'FIRSTHEALTH OF THE CAROLINAS',E'Firsthealth Of The Carolinas',null,null,E'firsthealth-of-the-carolinas');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (81,E'ELDERPLAN',E'Elderplan',null,null,E'elderplan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (82,E'MID ROGUE COMMUNITY HEALTH PLAN',E'Mid Rogue Community Health Plan',null,null,E'mid-rogue-community-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (83,E'CHINESE HOSPITAL ASSOCIATION',E'Chinese Hospital Association',null,null,E'chinese-hospital-association');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (84,E'ITASCA COUNTY HEALTH & HUMAN SERVICES',E'Itasca County Health & Human Services',null,null,E'itasca-county-health-&-human-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (85,E'BLUE CROSS OF IDAHO HEALTH SERVICES',E'Blue Cross Of Idaho Health Services',null,null,E'blue-cross-of-idaho-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (86,E'LUTHERAN SOCIAL SERVICES OF SOUTH CENTRAL PA',E'Lutheran Social Services Of South Central Pa',null,null,E'lutheran-social-services-of-south-central-pa');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (87,E'MCLAREN HLTH GRP',E'Mclaren Hlth Grp',null,null,E'mclaren-hlth-grp');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (88,E'PACE ORGANIZATION OF RHODE ISLAND',E'Pace Organization Of Rhode Island',null,null,E'pace-organization-of-rhode-island');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (89,E'PENNSYLVANIA PACE',E'Pennsylvania Pace',null,null,E'pennsylvania-pace');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (90,E'CARE RESOURCES',E'Care Resources',null,null,E'care-resources');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (91,E'HONORED CITIZENS CHOICE HEALTH PLAN',E'Honored Citizens Choice Health Plan',null,null,E'honored-citizens-choice-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (92,E'PREFERRED MEDICAL PLAN',E'Preferred Medical Plan',null,null,E'preferred-medical-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (93,E'LOS ANGELES JEWISH HOME FOR THE AGING',E'Los Angeles Jewish Home For The Aging',null,null,E'los-angeles-jewish-home-for-the-aging');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (94,E'SCAN HEALTH PLAN',E'Scan Health Plan',null,null,E'scan-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (95,E'CENTENE',E'Centene',null,null,E'centene');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (96,E'VOLUNTEERS OF AMERICA NATIONAL SERVICES',E'Volunteers Of America National Services',null,null,E'volunteers-of-america-national-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (97,E'PROVIDENCE HEALTH & SERVICES',E'Providence Health & Services',null,null,E'providence-health-&-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (98,E'EMBLEMHEALTH',E'Emblemhealth',null,null,E'emblemhealth');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (99,E'FRANCISCAN PACE',E'Franciscan Pace',null,null,E'franciscan-pace');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (100,E'HIGHMARK',E'Highmark',null,null,E'highmark');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (101,E'FLORIDA HEALTHCARE PLUS',E'Florida Healthcare Plus',null,null,E'florida-healthcare-plus');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (102,E'PACE @ HOME',E'Pace @ Home',null,null,E'pace-@-home');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (103,E'PALMETTO HEALTH ALLIANCE',E'Palmetto Health Alliance',null,null,E'palmetto-health-alliance');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (104,E'CUATRO LLC',E'Cuatro Llc',null,null,E'cuatro-llc');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (105,E'ESSENCE',E'Essence',null,null,E'essence');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (106,E'GEMCARE MERCY MEMORIAL HEALTH SYSTEM',E'Gemcare Mercy Memorial Health System',null,null,E'gemcare-mercy-memorial-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (107,E'JEWISH GUILD FOR THE BLIND',E'Jewish Guild For The Blind',null,null,E'jewish-guild-for-the-blind');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (108,E'MEDSTAR HEALTH',E'Medstar Health',null,null,E'medstar-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (109,E'CAPITAL DISTRICT PHYSICIANS'' HEALTH PLAN',E'Capital District Physicians'' Health Plan',null,null,E'capital-district-physicians''-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (110,E'ROCKY MOUNTAIN HMO INC',E'Rocky Mountain Hmo Inc',null,null,E'rocky-mountain-hmo-inc');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (111,E'CENTRA HEALTH',E'Centra Health',null,null,E'centra-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (112,E'SENIORLIFE WASHINGTON',E'Seniorlife Washington',null,null,E'seniorlife-washington');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (113,E'COMMUNITY HEALTH GROUP',E'Community Health Group',null,null,E'community-health-group');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (114,E'INDEPENDENT HEALTH ASSOCIATION',E'Independent Health Association',null,null,E'independent-health-association');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (115,E'ALBRIGHT CARE SERVICES',E'Albright Care Services',null,null,E'albright-care-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (116,E'BLUE CROSS AND BLUE SHIELD OF NORTH CAROLINA',E'Blue Cross And Blue Shield Of North Carolina',null,null,E'blue-cross-and-blue-shield-of-north-carolina');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (117,E'UNIVERSITY OF PITTSBURGH MEDICAL CENTER',E'University Of Pittsburgh Medical Center',null,null,E'university-of-pittsburgh-medical-center');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (118,E'BLUE CROSS BLUE SHIELD OF MICHIGAN',E'Blue Cross Blue Shield Of Michigan',null,null,E'blue-cross-blue-shield-of-michigan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (119,E'COMPREHENSIVE SENIOR CARE CORPORATION',E'Comprehensive Senior Care Corporation',null,null,E'comprehensive-senior-care-corporation');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (120,E'THE OKLAHOMA CITY CLINIC',E'The Oklahoma City Clinic',null,null,E'the-oklahoma-city-clinic');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (121,E'BLUE CROSS & BLUE SHIELD OF RHODE ISLAND',E'Blue Cross & Blue Shield Of Rhode Island',null,null,E'blue-cross-&-blue-shield-of-rhode-island');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (122,E'TRIPLE-S MANAGEMENT CORP',E'Triple-S Management Corp',null,null,E'triple-s-management-corp');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (123,E'TUFTS ASSOCIATED HEALTH PLANS',E'Tufts Associated Health Plans',null,null,E'tufts-associated-health-plans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (124,E'MCGREGOR AT OVERLOOK',E'Mcgregor At Overlook',null,null,E'mcgregor-at-overlook');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (125,E'ACENSION HEALTH',E'Acension Health',null,null,E'acension-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (126,E'MARICOPA COUNTY SPECIAL HEALTH CARE DISTRICT',E'Maricopa County Special Health Care District',null,null,E'maricopa-county-special-health-care-district');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (127,E'PREMERA',E'Premera',null,null,E'premera');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (128,E'ROCKY MOUNTAIN HEALTH CARE SERVICES',E'Rocky Mountain Health Care Services',null,null,E'rocky-mountain-health-care-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (129,E'HEALTH PLAN OF THE UPPER OHIO VALLEY',E'Health Plan Of The Upper Ohio Valley',null,null,E'health-plan-of-the-upper-ohio-valley');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (130,E'AIDS HEALTHCARE FOUNDATION',E'Aids Healthcare Foundation',null,null,E'aids-healthcare-foundation');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (131,E'AMARILLO MULTISVC CTR FOR THE AGING',E'Amarillo Multisvc Ctr For The Aging',null,null,E'amarillo-multisvc-ctr-for-the-aging');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (132,E'CATHOLIC HEALTH EAST',E'Catholic Health East',null,null,E'catholic-health-east');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (133,E'HEALTHSUN HEALTH PLANS',E'Healthsun Health Plans',null,null,E'healthsun-health-plans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (134,E'ROCHESTER GENERAL HOSPITAL',E'Rochester General Hospital',null,null,E'rochester-general-hospital');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (135,E'COMMUNITY HEALTH PLAN OF WASHINGTON',E'Community Health Plan Of Washington',null,null,E'community-health-plan-of-washington');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (136,E'SENIOR LIFE ALTOONA',E'Senior Life Altoona',null,null,E'senior-life-altoona');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (137,E'MERCY MEDICAL',E'Mercy Medical',null,null,E'mercy-medical');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (138,E'APPALACHIAN AGENCY FOR SENIOR CITIZENS',E'Appalachian Agency For Senior Citizens',null,null,E'appalachian-agency-for-senior-citizens');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (139,E'COMMUNITY CARE OF WESTERN NEW YORK',E'Community Care Of Western New York',null,null,E'community-care-of-western-new-york');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (140,E'NEW WEST HEALTH SERVICES',E'New West Health Services',null,null,E'new-west-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (141,E'THE LUTHERAN HOME FOR THE AGED',E'The Lutheran Home For The Aged',null,null,E'the-lutheran-home-for-the-aged');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (142,E'VERITAGE LLC',E'Veritage Llc',null,null,E'veritage-llc');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (143,E'CENTER FOR ELDERS INDEPENDENCE',E'Center For Elders Independence',null,null,E'center-for-elders-independence');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (144,E'FALLON COMMUNITY HEALTH PLAN',E'Fallon Community Health Plan',null,null,E'fallon-community-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (145,E'KAISER FOUNDATION HEALTH PLAN',E'Kaiser Foundation Health Plan',null,null,E'kaiser-foundation-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (146,E'HEALTH ALLIANCE PLAN (HAP)',E'Health Alliance Plan (Hap)',null,null,E'health-alliance-plan-(hap)');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (147,E'TRUSTEES OF THE UNIVERSITY OF PENNSYLVANIA',E'Trustees Of The University Of Pennsylvania',null,null,E'trustees-of-the-university-of-pennsylvania');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (148,E'CATHOLIC CHARITIES ARCHDIOCESE OF NEW ORLEANS',E'Catholic Charities Archdiocese Of New Orleans',null,null,E'catholic-charities-archdiocese-of-new-orleans');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (149,E'HEALTHPLUS OF MICHIGAN',E'Healthplus Of Michigan',null,null,E'healthplus-of-michigan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (150,E'LIFETIME HEALTHCARE',E'Lifetime Healthcare',null,null,E'lifetime-healthcare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (151,E'HOPE HOSPICE AND COMMUNITY SERVICE',E'Hope Hospice And Community Service',null,null,E'hope-hospice-and-community-service');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (152,E'ON LOK SENIOR HEALTH SERVICES',E'On Lok Senior Health Services',null,null,E'on-lok-senior-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (153,E'AGATE RESOURCES',E'Agate Resources',null,null,E'agate-resources');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (154,E'HARBOR HEALTH SERVICES',E'Harbor Health Services',null,null,E'harbor-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (155,E'PH HOLDINGS',E'Ph Holdings',null,null,E'ph-holdings');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (156,E'HEALTH PLAN OF SAN MATEO',E'Health Plan Of San Mateo',null,null,E'health-plan-of-san-mateo');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (157,E'MARQUETTE GENERAL HOSPITAL',E'Marquette General Hospital',null,null,E'marquette-general-hospital');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (158,E'HEALTH ASSOCIATION OF NIAGARA COUNTY',E'Health Association Of Niagara County',null,null,E'health-association-of-niagara-county');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (159,E'IMMANUEL PATHWAYS',E'Immanuel Pathways',null,null,E'immanuel-pathways');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (160,E'VIA CHRISTI OUTREACH PGRM. ELDERS',E'Via Christi Outreach Pgrm. Elders',null,null,E'via-christi-outreach-pgrm.-elders');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (161,E'CAIDAN ENTERPRISES INC GRP',E'Caidan Enterprises Inc Grp',null,null,E'caidan-enterprises-inc-grp');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (162,E'ST. MARY MEDICAL CENTER',E'St. Mary Medical Center',null,null,E'st.-mary-medical-center');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (163,E'VANGUARD HEALTH SYSTEMS',E'Vanguard Health Systems',null,null,E'vanguard-health-systems');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (164,E'LIBERTY HEALTH ADVANTAGE',E'Liberty Health Advantage',null,null,E'liberty-health-advantage');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (165,E'LIVING INDEPENDENCE FOR THE ELDERLY',E'Living Independence For The Elderly',null,null,E'living-independence-for-the-elderly');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (167,E'UNIVERSAL AMERICAN CORP',E'Universal American Corp',null,null,E'universal-american-corp');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (168,E'SENIOR LIFE GREENSBURG',E'Senior Life Greensburg',null,null,E'senior-life-greensburg');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (169,E'PRESBYTERIAN HEALTHCARE SERVICES',E'Presbyterian Healthcare Services',null,null,E'presbyterian-healthcare-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (170,E'HEALTH PARTNERS OF PHILADELPHIA',E'Health Partners Of Philadelphia',null,null,E'health-partners-of-philadelphia');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (171,E'INDIANA UNIVERSITY HEALTH',E'Indiana University Health',null,null,E'indiana-university-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (172,E'COMMUNITYCARE MANAGED HEALTHCARE PLANS OF OK',E'Communitycare Managed Healthcare Plans Of Ok',null,null,E'communitycare-managed-healthcare-plans-of-ok');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (173,E'CONTRA COSTA HEALTH SERVICES',E'Contra Costa Health Services',null,null,E'contra-costa-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (174,E'LOCAL INITIATIVE HEALTH AUTHORITY FOR LA CTY',E'Local Initiative Health Authority For La Cty',null,null,E'local-initiative-health-authority-for-la-cty');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (175,E'ELDER SERVICE PLAN OF THE NORTH SHORE',E'Elder Service Plan Of The North Shore',null,null,E'elder-service-plan-of-the-north-shore');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (176,E'FIRST MEDICAL HEALTH PLAN',E'First Medical Health Plan',null,null,E'first-medical-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (177,E'FIDELIS SECURECARE',E'Fidelis Securecare',null,null,E'fidelis-securecare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (178,E'INTERMOUNTAIN HEALTH CARE',E'Intermountain Health Care',null,null,E'intermountain-health-care');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (179,E'LORETTO REST REALTY CORPORATION',E'Loretto Rest Realty Corporation',null,null,E'loretto-rest-realty-corporation');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (180,E'RENOWN HEALTH',E'Renown Health',null,null,E'renown-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (181,E'INNOVA HEALTH SYSTEMS',E'Innova Health Systems',null,null,E'innova-health-systems');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (182,E'LIFE ST JOSEPH OF THE PINES',E'Life St Joseph Of The Pines',null,null,E'life-st-joseph-of-the-pines');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (183,E'COLORADO ACCESS',E'Colorado Access',null,null,E'colorado-access');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (184,E'UAB HEALTH SYSTEM',E'Uab Health System',null,null,E'uab-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (185,E'WELLPOINT',E'Wellpoint',null,null,E'wellpoint');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (186,E'PARTNERSHIP HEALTHPLAN OF CALIFORNIA',E'Partnership Healthplan Of California',null,null,E'partnership-healthplan-of-california');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (187,E'ALPHACARE HOLDINGS',E'Alphacare Holdings',null,null,E'alphacare-holdings');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (188,E'UNITED CHURCH HOMES & SERVICES',E'United Church Homes & Services',null,null,E'united-church-homes-&-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (189,E'COMMUNITY CARE',E'Community Care',null,null,E'community-care');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (190,E'MEDICAL CARD SYSTEM',E'Medical Card System',null,null,E'medical-card-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (191,E'USABLE MUTUAL INSURANCE CO',E'Usable Mutual Insurance Co',null,null,E'usable-mutual-insurance-co');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (192,E'HARVARD PILGRIM HEALTH CARE',E'Harvard Pilgrim Health Care',null,null,E'harvard-pilgrim-health-care');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (193,E'HEALTHPARTNERS',E'Healthpartners',null,null,E'healthpartners');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (194,E'SOUTHWEST CATHOLIC HEALTH NETWORK',E'Southwest Catholic Health Network',null,null,E'southwest-catholic-health-network');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (195,E'THE METHODIST OAKS',E'The Methodist Oaks',null,null,E'the-methodist-oaks');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (196,E'COMMONWEALTH CARE ALLIANCE',E'Commonwealth Care Alliance',null,null,E'commonwealth-care-alliance');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (197,E'CONSTELLATION HEALTH',E'Constellation Health',null,null,E'constellation-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (198,E'SENTARA HEALTHCARE',E'Sentara Healthcare',null,null,E'sentara-healthcare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (199,E'SCOTT AND WHITE',E'Scott And White',null,null,E'scott-and-white');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (200,E'MEMORIAL HOSPITAL OF LARAMIE COUNTY',E'Memorial Hospital Of Laramie County',null,null,E'memorial-hospital-of-laramie-county');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (201,E'HEALTH FIRST',E'Health First',null,null,E'health-first');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (202,E'CAPITAL BLUECROSS',E'Capital Bluecross',null,null,E'capital-bluecross');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (203,E'ALAMEDA ALLIANCE FOR HEALTH',E'Alameda Alliance For Health',null,null,E'alameda-alliance-for-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (204,E'INTERVALLEY HEALTH PLAN',E'Intervalley Health Plan',null,null,E'intervalley-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (205,E'PIEDMONT COMMUNITY HEALTH PLAN',E'Piedmont Community Health Plan',null,null,E'piedmont-community-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (206,E'ST. BERNARD''S HEALTHCARE',E'St. Bernard''S Healthcare',null,null,E'st.-bernard''s-healthcare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (207,E'FAMILYCARE INCORPORATED',E'Familycare Incorporated',null,null,E'familycare-incorporated');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (208,E'BLUE CROSS AND BLUE SHIELD OF MASSACHUSETTS',E'Blue Cross And Blue Shield Of Massachusetts',null,null,E'blue-cross-and-blue-shield-of-massachusetts');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (209,E'AFFINITY HEALTH SYSTEM',E'Affinity Health System',null,null,E'affinity-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (210,E'MERCY HEALTH ALLIANCE',E'Mercy Health Alliance',null,null,E'mercy-health-alliance');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (211,E'RIVERSIDE RETIREMENT SERVICES',E'Riverside Retirement Services',null,null,E'riverside-retirement-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (212,E'HORIZON BLUE CROSS BLUE SHIELD OF NEW JERSEY',E'Horizon Blue Cross Blue Shield Of New Jersey',null,null,E'horizon-blue-cross-blue-shield-of-new-jersey');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (213,E'IMMANUEL',E'Immanuel',null,null,E'immanuel');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (214,E'MEDICAL ASSOCIATES CLINIC',E'Medical Associates Clinic',null,null,E'medical-associates-clinic');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (215,E'LIFECIRCLES',E'Lifecircles',null,null,E'lifecircles');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (216,E'AULTMAN HEALTH FOUNDATION',E'Aultman Health Foundation',null,null,E'aultman-health-foundation');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (217,E'NEWCOURTLAND LIFE PROGRAM',E'Newcourtland Life Program',null,null,E'newcourtland-life-program');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (218,E'SANFORD HEALTH PLAN',E'Sanford Health Plan',null,null,E'sanford-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (219,E'UPHAMS CORNER HEALTH COMMITTEE',E'Uphams Corner Health Committee',null,null,E'uphams-corner-health-committee');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (220,E'VANTAGE  HEALTH PLAN',E'Vantage  Health Plan',null,null,E'vantage--health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (221,E'HEALTH CARE SERVICE CORPORATION',E'Health Care Service Corporation',null,null,E'health-care-service-corporation');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (222,E'JOHNS HOPKINS HEALTH SYSTEM',E'Johns Hopkins Health System',null,null,E'johns-hopkins-health-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (223,E'GOLDEN STATE MEDICARE HEALTH PLAN',E'Golden State Medicare Health Plan',null,null,E'golden-state-medicare-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (224,E'IASIS HEALTHCARE',E'Iasis Healthcare',null,null,E'iasis-healthcare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (225,E'BIENVIVIR SENIOR HEALTH SERVICES',E'Bienvivir Senior Health Services',null,null,E'bienvivir-senior-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (226,E'GUNDERSON LUTHERAN',E'Gunderson Lutheran',null,null,E'gunderson-lutheran');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (227,E'HEALTH NET',E'Health Net',null,null,E'health-net');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (228,E'PIEDMONT HEALTH SERVICES',E'Piedmont Health Services',null,null,E'piedmont-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (229,E'AETNA',E'Aetna',null,null,E'aetna');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (230,E'INDEPENDENT CARE HEALTH PLAN',E'Independent Care Health Plan',null,null,E'independent-care-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (231,E'TOTAL HEALTH CARE',E'Total Health Care',null,null,E'total-health-care');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (232,E'TRIHEALTH SENIORLINK',E'Trihealth Seniorlink',null,null,E'trihealth-seniorlink');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (234,E'ORANGE COUNTY HEALTH AUTHORITY',E'Orange County Health Authority',null,null,E'orange-county-health-authority');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (235,E'HEALTHNOW NEW YORK',E'Healthnow New York',null,null,E'healthnow-new-york');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (236,E'TOTAL COMMUNITY OPTIONS',E'Total Community Options',null,null,E'total-community-options');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (237,E'ADVANTAGE HEALTH SOLUTIONS',E'Advantage Health Solutions',null,null,E'advantage-health-solutions');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (239,E'ALTAMED HEALTH SERVICES',E'Altamed Health Services',null,null,E'altamed-health-services');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (240,E'DENVER HEALTH MEDICAL CENTER',E'Denver Health Medical Center',null,null,E'denver-health-medical-center');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (241,E'UNITEDHEALTH GROUP',E'Unitedhealth Group',null,null,E'unitedhealth-group');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (242,E'PACIFICSOURCE HEALTH PLAN',E'Pacificsource Health Plan',null,null,E'pacificsource-health-plan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (244,E'TRINITY HEALTH',E'Trinity Health',null,null,E'trinity-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (245,E'CENTRAL HEALTH PLAN OF CALIFORNIA',E'Central Health Plan Of California',null,null,E'central-health-plan-of-california');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (246,E'IDJB INVESTMENTS',E'Idjb Investments',null,null,E'idjb-investments');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (247,E'CATHOLIC HEALTH CARE SYSTEM',E'Catholic Health Care System',null,null,E'catholic-health-care-system');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (248,E'MIDLAND CARE CONNECTION',E'Midland Care Connection',null,null,E'midland-care-connection');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (249,E'AMERICA''S 1ST CHOICE HOLDINGS OF FLORIDA',E'America''S 1st Choice Holdings Of Florida',null,null,E'america''s-1st-choice-holdings-of-florida');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (250,E'ALOHACARE',E'Alohacare',null,null,E'alohacare');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (251,E'LUBBOCK REGIONAL MENTAL HEALTH',E'Lubbock Regional Mental Health',null,null,E'lubbock-regional-mental-health');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (252,E'HEALTH SERVICES GROUP',E'Health Services Group',null,null,E'health-services-group');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (253,E'PACE OF SOUTHWEST MICHIGAN',E'Pace Of Southwest Michigan',null,null,E'pace-of-southwest-michigan');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (254,E'BLUECROSS BLUESHIELD OF TENNESSEE',E'Bluecross Blueshield Of Tennessee',null,null,E'bluecross-blueshield-of-tennessee');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (255,E'THE HOSPICE OF FLORIDA SUNCOAST',E'The Hospice Of Florida Suncoast',null,null,E'the-hospice-of-florida-suncoast');
INSERT INTO companies(id, name_upper, name_proper, created_at, updated_at, slug) VALUES (1,E'CARE WISCONSIN FIRST',E'Care Wisconsin First',null,null,E'care-wisconsin-first');
